### ISSUE TITLE
Heroku push rejected using Buildpack heroku-buildpack-tex

### ISSUE THREAD

**Issue by aardvarkk** [gulopine/heroku-buildpack-tex#4]
I'm receiving the following message when trying to push to Heroku using this Buildpack:

=====> Downloading Buildpack: https://github.com/holiture/heroku-buildpack-tex
 !     Heroku push rejected, failed to compile Multipack app

Of note is that I'm using this Buildpack as part of a Multipack (https://github.com/ddollar/heroku-buildpack-multi)

My .buildpacks file looks like this:

https://github.com/heroku/heroku-buildpack-ruby
https://github.com/holiture/heroku-buildpack-tex

Pretty straightforward -- just trying to install TeX along with the RoR buildpack. Are there any other error messages or places to look as to why this is failing?

**Comment by gulopine** [comment]
Well, there are probably two problems here. First, the one I know about. For whatever reason, this buildpack hasn't worked with Heroku in a while. It was a side project that I apparently messed up at some point, and I haven't had the time to work out what's going wrong with it. TeX and LaTeX commands simply don't work at the moment, even if the buildpack were installing correctly.

Second, the one I'm speculating about. I've never tried a multipack, but I can almost guarantee that this won't work well with that approach. This buildpack expects a document.tex in your repository, which will be compiled as soon as Heroku receives the push. It's not at all meant to simply install TeX onto a system in a way that can be used by another app. That's a pretty good idea, but this buildpack (as it is now) won't do that. It's probably failing to compile because it either can't find document.tex or because of the problems I mentioned above. And if it doesn't succeed compilation, it'll probably throw the error you described, because Multipack probably expects both buildpacks to compile successfully in order to succeed.

I admit, there are definitely some problems with this that should be addressed before anybody tries to use it. I'll try to make that clear on the front page, so there are no illusions about it. However, I just don't think what you're trying to do is compatible with the way the buildpack is meant to work, so I'm going to go ahead and close this issue.

**Comment by hammady** [comment]
Your same exact setup now works for me. The only thing you need to do is to swap the 2 lines in .buildpacks because Multiplacks defines its process types from the last buildpack (web, worker, console, rake). Oh one thing more, I had to start a web dyno manually by typing: heroku ps:scale web=1
